name: Video Orchestrator | CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_NAME: fiapx-orchestrator
  EKS_CLUSTER_NAME: soat-challenge-eks-cluster
  K8S_DEPLOYMENT_NAME: orchestrator-deployment
  K8S_CONTAINER_NAME: orchestrator

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Validar Build (Compilação)
        run: npm run build

      - name: Rodar testes com cobertura
        run: npm run test:cov
        env:
          NODE_ENV: test
          PORT: 3000

          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: video_processor_db_test

          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          AWS_ENDPOINT: http://localhost:4566
          AWS_S3_FORCE_PATH_STYLE: "true"

          AWS_S3_BUCKET_RAW: fiap-x-raw
          AWS_SQS_UPLOAD_QUEUE_URL: http://localhost:4566/000000000000/upload-events-queue
          AWS_SQS_PROCESSING_QUEUE_URL: http://localhost:4566/000000000000/video-processing-queue
          AWS_SQS_RESULT_QUEUE_URL: http://localhost:4566/000000000000/video-result-queue
          AWS_SQS_EMAIL_QUEUE_URL: http://localhost:4566/000000000000/email-notification-queue

          JWT_SECRET: segredo_temporario_ci_test

  build_and_deploy:
    needs: quality_check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Fazer login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir e enviar a imagem Docker para o ECR
        run: |
          IMAGE_URI_LATEST=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:latest
          IMAGE_URI_SHA=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}

          echo "Building image..."
          docker build -t $IMAGE_URI_LATEST -t $IMAGE_URI_SHA .

          echo "Pushing images..."
          docker push $IMAGE_URI_LATEST
          docker push $IMAGE_URI_SHA

      - name: Configurar o kubeconfig para o cluster EKS
        run: aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Implantação no EKS
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}

          kubectl set image deployment/${{ env.K8S_DEPLOYMENT_NAME }} ${{ env.K8S_CONTAINER_NAME }}="$IMAGE_URI"

          kubectl rollout restart deployment/${{ env.K8S_DEPLOYMENT_NAME }}

          kubectl rollout status deployment/${{ env.K8S_DEPLOYMENT_NAME }}
